### ISSUE TITLE
Varchar size

### ISSUE THREAD

**Issue by patrykcelinski** [SuperXtra/NotepadApi#3]
https://github.com/SuperXtra/NotepadApi/blob/be211e4f50aaee61a7bcfeb548bd2376fccf6aa6/conf/evolutions/default/1.sql#L5

I noticed one odd thing. Why your varchar fields don't have a size specified? Like `VARCHAR(255)`? I'm not sure how is it possible but for sure it is not performant - SQL likes to know the size of the fields so it can store them in structured way.

**Comment by SuperXtra** [comment]
Correct, confirmed!
https://stackoverflow.com/questions/8295131/best-practices-for-sql-varchar-column-length
