### ISSUE TITLE
Use proper names

### ISSUE THREAD

**Issue by patrykcelinski** [SuperXtra/NotepadApi#6]
https://github.com/SuperXtra/NotepadApi/blob/be211e4f50aaee61a7bcfeb548bd2376fccf6aa6/conf/evolutions/default/1.sql#L1

`evloutions` is a strange name. It would be better to use `db` or `migrations`>

`1.sql` also is strange. In most of migration tools you have descriptive names:
`20170608_CreateUsersAndNotes // EF - C#`
`src/main/resources/db/migration/V1__Create_person_table.sql // flyway - java,scala`

**Comment by patrykcelinski** [comment]
```
  "com.typesafe.play" %% "play-slick-evolutions" % "4.0.0"
```

That is why you use `evolutions` name. Its slick migrator. Let's hope that there is an option to change the folder name.

**Comment by SuperXtra** [comment]
yees same with 0 in model as id, need to think about doobie next time
